services:
  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data:/data"
  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      .env
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"