"""add dialogues and triggers

Revision ID: 421929f65412
Revises: f1fedbf1bfd1
Create Date: 2024-03-17 15:27:22.345908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421929f65412'
down_revision: Union[str, None] = 'f1fedbf1bfd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triggers',
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('TEXT', 'COMMAND', 'BUTTON', name='triggereventtype'), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('trigger_id')
    )
    op.create_table('dialogues',
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.trigger_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dialogue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialogues')
    op.drop_table('triggers')
    op.execute('DROP TYPE triggereventtype;')
    # ### end Alembic commands ###
