"""add dialogue blocks

Revision ID: 4957afca1d16
Revises: 421929f65412
Create Date: 2024-03-19 21:30:24.388898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4957afca1d16'
down_revision: Union[str, None] = '421929f65412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogues.dialogue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id'),
    sa.UniqueConstraint('dialogue_id', 'sequence_number')
    )
    op.create_table('api_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('http_method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'CONNECT', 'HEAD', 'OPTIONS', name='httpmethod'), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('csv_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('email_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('text', sa.String(length=8192), nullable=False),
    sa.Column('recipient_email', sa.String(length=254), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('image_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('question_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(length=4096), nullable=False),
    sa.Column('answer_type', sa.Enum('ANY', 'TEXT', 'INT', 'EMAIL', 'PHONE_NUMBER', name='answermessagetype'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('text_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_blocks')
    op.drop_table('question_blocks')
    op.drop_table('image_blocks')
    op.drop_table('email_blocks')
    op.drop_table('csv_blocks')
    op.drop_table('api_blocks')
    op.drop_table('blocks')
    op.execute('DROP TYPE httpmethod;')
    op.execute('DROP TYPE answermessagetype;')
    # ### end Alembic commands ###
