"""add plugins

Revision ID: 65482dfbd288
Revises: 70b5f6fc7b68
Create Date: 2024-03-29 12:06:22.588859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65482dfbd288'
down_revision: Union[str, None] = '70b5f6fc7b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('handlers_file_path', sa.String(length=256), nullable=False),
    sa.Column('db_funcs_file_path', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('plugin_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects_plugins',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.plugin_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'plugin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_plugins')
    op.drop_table('plugins')
    # ### end Alembic commands ###
