"""add projects start message and keyboard

Revision ID: 70b5f6fc7b68
Revises: 4957afca1d16
Create Date: 2024-03-24 19:30:15.246888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b5f6fc7b68'
down_revision: Union[str, None] = '4957afca1d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

keyboard_type = sa.Enum('INLINE_KEYBOARD', 'REPLY_KEYBOARD', name='keyboardtype')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    keyboard_type.create(op.get_bind())
    op.add_column('projects', sa.Column('start_message', sa.String(length=4096), nullable=False))
    op.add_column('projects', sa.Column('start_keyboard_type', keyboard_type, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'start_keyboard_type')
    op.drop_column('projects', 'start_message')
    op.execute('DROP TYPE keyboardtype;')
    # ### end Alembic commands ###

