"""add dialogue templates

Revision ID: 8049321ce790
Revises: 65482dfbd288
Create Date: 2024-05-10 00:39:20.752983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8049321ce790'
down_revision: Union[str, None] = '65482dfbd288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogues.dialogue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('dialogues', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plugins', 'image_path',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugins', 'image_path',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('dialogues', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('templates')
    # ### end Alembic commands ###
